name: ahamai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.18.1
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  markdown: ^7.1.1
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.2
  url_launcher: ^6.3.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.2
  file_picker: ^8.0.0+1
  archive: ^3.4.8
  syncfusion_flutter_pdf: ^23.2.7
  provider: ^6.1.1
  fl_chart: ^0.69.0
  device_info_plus: ^10.1.0
  webview_flutter: ^4.4.2
  share_plus: ^10.1.2




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true