name: ahamai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.2
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  http: ^1.1.0
  provider: ^6.1.1
  url_launcher: ^6.2.1
  syncfusion_flutter_pdf: ^23.2.7
  flutter_tts: ^3.8.5
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  archive: ^3.4.9
  flutter_deck: ^0.19.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true