name: ahamai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.20.1
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.5.2
  flutter_markdown: ^0.6.23



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true