import 'dart:io';
import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:share_plus/share_plus.dart';

class ExternalToolsService {
  /// Execute a file creation tool
  static Future<Map<String, dynamic>> executeFileTool({
    required String operation,
    required String fileName,
    required String content,
    String? fileType,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      // Determine file type from extension if not provided
      final actualFileType = fileType ?? fileName.split('.').last.toLowerCase();
      
      // Ensure proper file extension
      String finalFileName = fileName;
      if (!fileName.toLowerCase().endsWith('.${actualFileType}')) {
        finalFileName = '$fileName.$actualFileType';
      }
      
      // Use external Downloads directory so files are visible in device
      Directory targetDir;
      try {
        if (Platform.isAndroid) {
          // Try to use Downloads directory
          targetDir = Directory('/storage/emulated/0/Download');
          if (!targetDir.existsSync()) {
            // Fallback to external storage
            final externalDir = await getExternalStorageDirectory();
            if (externalDir != null) {
              targetDir = Directory('${externalDir.path}/Download');
            } else {
              // Last resort - app documents
              targetDir = await getApplicationDocumentsDirectory();
            }
          }
        } else {
          // iOS - use documents directory
          targetDir = await getApplicationDocumentsDirectory();
        }
        
        // Create directory if it doesn't exist
        if (!targetDir.existsSync()) {
          targetDir.createSync(recursive: true);
        }
      } catch (e) {
        // Fallback to app documents directory
        targetDir = await getApplicationDocumentsDirectory();
      }
      
      final file = File('${targetDir.path}/$finalFileName');
      
      String finalContent = content;
      String mimeType = 'text/plain';
      
      // Handle different file types with proper formatting
      switch (actualFileType) {
        case 'html':
          mimeType = 'text/html';
          if (!content.toLowerCase().contains('<html>')) {
            finalContent = '''<!DOCTYPE html>
<html>
<head>
    <title>${metadata?['title'] ?? 'Document'}</title>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
        pre { white-space: pre-wrap; background: #f5f5f5; padding: 10px; border-radius: 5px; }
    </style>
</head>
<body>
    <h1>${metadata?['title'] ?? 'Document'}</h1>
    <div>$content</div>
</body>
</html>''';
          }
          break;
        case 'css':
          mimeType = 'text/css';
          if (!content.toLowerCase().contains('/*')) {
            finalContent = '''/* Generated CSS File */
/* Title: ${metadata?['title'] ?? 'Styles'} */

$content''';
          }
          break;
        case 'json':
          mimeType = 'application/json';
          try {
            final jsonData = json.decode(content);
            finalContent = const JsonEncoder.withIndent('  ').convert(jsonData);
          } catch (e) {
            finalContent = '''{"content": ${json.encode(content)},"created_at": "${DateTime.now().toIso8601String()}","title": "${metadata?['title'] ?? 'Document'}"}''';
          }
          break;
        case 'xml':
          mimeType = 'application/xml';
          if (!content.toLowerCase().contains('<?xml')) {
            finalContent = '''<?xml version="1.0" encoding="UTF-8"?>
<document>
  <title>${metadata?['title'] ?? 'Document'}</title>
  <content>$content</content>
  <created>${DateTime.now().toIso8601String()}</created>
</document>''';
          }
          break;
        case 'md':
        case 'markdown':
          mimeType = 'text/markdown';
          if (!content.startsWith('#')) {
            finalContent = '''# ${metadata?['title'] ?? 'Document'}

$content

---
*Generated by AhamAI on ${DateTime.now().toString()}*''';
          }
          break;
        case 'pdf':
          // For PDF, create HTML that can be converted
          mimeType = 'text/html';
          finalFileName = finalFileName.replaceAll('.pdf', '.html');
          finalContent = '''<!DOCTYPE html>
<html>
<head>
    <title>${metadata?['title'] ?? 'Document'}</title>
    <meta charset="UTF-8">
    <style>
        @page { margin: 1in; }
        body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.5; }
        h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
        pre { white-space: pre-wrap; font-family: 'Courier New', monospace; }
    </style>
</head>
<body>
    <h1>${metadata?['title'] ?? 'Document'}</h1>
    <div>$content</div>
    <br><br>
    <p><small>Generated on ${DateTime.now().toString()}</small></p>
</body>
</html>''';
          break;
        case 'txt':
        default:
          mimeType = 'text/plain';
          // Keep content as-is for txt files
          break;
      }
      
      // Write the file
      await file.writeAsString(finalContent, encoding: utf8);
      
      return {
        'success': true,
        'message': 'File created successfully: $finalFileName',
        'file_path': file.path,
        'file_name': finalFileName,
        'file_size': await file.length(),
        'mime_type': mimeType,
        'file_type': actualFileType,
        'created_at': DateTime.now().toIso8601String(),
        'is_external': targetDir.path.contains('/storage/emulated/0/Download'),
      };
      
    } catch (e) {
      return {
        'success': false,
        'error': 'Failed to create file: $e',
        'file_name': fileName,
      };
    }
  }
  
  /// Share a file via different methods
  static Future<Map<String, dynamic>> shareFile({
    required String filePath,
    required String shareMethod,
    String? recipient,
    String? subject,
    String? message,
  }) async {
    try {
      final file = File(filePath);
      if (!file.existsSync()) {
        return {
          'success': false,
          'error': 'File does not exist: $filePath',
        };
      }

      final fileName = file.path.split('/').last;
      final fileSize = await file.length();
      final fileExtension = fileName.split('.').last.toLowerCase();
      
      // Determine MIME type
      String mimeType = 'text/plain';
      switch (fileExtension) {
        case 'html':
          mimeType = 'text/html';
          break;
        case 'css':
          mimeType = 'text/css';
          break;
        case 'json':
          mimeType = 'application/json';
          break;
        case 'xml':
          mimeType = 'application/xml';
          break;
        case 'md':
        case 'markdown':
          mimeType = 'text/markdown';
          break;
        case 'pdf':
          mimeType = 'application/pdf';
          break;
        default:
          mimeType = 'text/plain';
      }
      
      switch (shareMethod) {
        case 'email':
          // Use Share.shareXFiles for email with proper MIME type
          await Share.shareXFiles(
            [XFile(filePath, mimeType: mimeType)], 
            text: message ?? 'Please find the attached file.',
            subject: subject ?? 'File from AhamAI: $fileName',
          );
          return {
            'success': true,
            'message': 'Email app opened with file attachment: $fileName',
            'file_name': fileName,
            'file_size': '${(fileSize / 1024).toStringAsFixed(1)} KB',
          };
          
        case 'whatsapp':
          return await _shareViaWhatsApp(file, recipient, message, mimeType);
          
        case 'sms':
          // SMS doesn't support file attachments, so share file content as text for small files
          if (fileSize < 500000) { // Less than 500KB
            final content = await file.readAsString();
            final truncatedContent = content.length > 1000 
              ? '${content.substring(0, 1000)}...\n\n[File: $fileName - Content truncated]'
              : content;
            return await executeCommunicationTool(
              operation: 'send_sms',
              recipient: recipient ?? '',
              content: message ?? 'File: $fileName\n\n$truncatedContent',
            );
          } else {
            return {
              'success': false,
              'error': 'File too large for SMS. Please use email or WhatsApp.',
            };
          }
          
        case 'share':
        default:
          // Generic share (opens system share dialog)
          await Share.shareXFiles(
            [XFile(filePath, mimeType: mimeType)], 
            text: message ?? 'Shared via AhamAI: $fileName'
          );
          return {
            'success': true,
            'message': 'File shared successfully: $fileName',
            'file_name': fileName,
          };
      }
      
    } catch (e) {
      return {
        'success': false,
        'error': 'Failed to share file: $e',
      };
    }
  }
  
  /// Share a file via email using Android intent with attachment
  static Future<Map<String, dynamic>> shareFileViaEmail({
    required String filePath,
    required String recipient,
    String? subject,
    String? message,
  }) async {
    if (Platform.isAndroid) {
      try {
        const emailChannel = MethodChannel('com.ahamai.email_intent');
        final result = await emailChannel.invokeMethod('sendEmailWithAttachment', {
          'recipient': recipient,
          'subject': subject ?? 'File from AhamAI',
          'body': message ?? 'Please find the attached file.',
          'filePath': filePath,
        });
        
        if (result['success'] == true) {
          final fileName = filePath.split('/').last;
          return {
            'success': true,
            'message': 'Email app opened with file attachment: $fileName',
            'method': 'android_intent_attachment',
          };
        } else {
          return {
            'success': false,
            'error': result['error'] ?? 'Failed to open email with attachment',
          };
        }
      } catch (e) {
        return {
          'success': false,
          'error': 'Android email intent failed: $e',
        };
      }
    }
    
    // Fallback to regular file sharing for non-Android
    return await shareFile(
      filePath: filePath,
      shareMethod: 'email',
      recipient: recipient,
      subject: subject,
      message: message,
    );
  }
  
  static Future<Map<String, dynamic>> _shareViaWhatsApp(File file, String? recipient, String? message, String mimeType) async {
    try {
      final fileName = file.path.split('/').last;
      final fileSize = await file.length();
      
      if (fileSize > 100 * 1024 * 1024) { // 100MB limit for WhatsApp
        return {
          'success': false,
          'error': 'File too large for WhatsApp (max 100MB)',
        };
      }
      
      // Use XFile with proper MIME type for WhatsApp sharing
      await Share.shareXFiles(
        [XFile(file.path, mimeType: mimeType)],
        text: message ?? 'File shared via AhamAI: $fileName',
      );
      
      return {
        'success': true,
        'message': 'WhatsApp opened with file attachment: $fileName',
        'file_name': fileName,
        'file_size': '${(fileSize / 1024).toStringAsFixed(1)} KB',
      };
      
    } catch (e) {
      return {
        'success': false,
        'error': 'Failed to share via WhatsApp: $e',
      };
    }
  }
  
  /// Execute a communication tool (email, WhatsApp, SMS)
  static Future<Map<String, dynamic>> executeCommunicationTool({
    required String operation,
    required String recipient,
    required String content,
    String? subject,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      switch (operation) {
        case 'send_email':
          return await _handleEmailLaunching(recipient, content, subject);
          
        case 'send_whatsapp':
          // Clean phone number (remove spaces, hyphens, etc.)
          final cleanPhone = recipient.replaceAll(RegExp(r'[^\d+]'), '');
          final urlToLaunch = 'https://wa.me/$cleanPhone?text=${Uri.encodeComponent(content)}';
          return await _launchUrl(urlToLaunch, 'WhatsApp');
          
        case 'send_sms':
          // Clean phone number
          final cleanPhone = recipient.replaceAll(RegExp(r'[^\d+]'), '');
          final urlToLaunch = Platform.isIOS 
            ? 'sms:$cleanPhone&body=${Uri.encodeComponent(content)}'
            : 'sms:$cleanPhone?body=${Uri.encodeComponent(content)}';
          return await _launchUrl(urlToLaunch, 'SMS');
          
        default:
          return {
            'success': false,
            'error': 'Unknown operation: $operation',
          };
      }
      
    } catch (e) {
      return {
        'success': false,
        'error': 'Communication tool execution failed: $e',
      };
    }
  }

  /// Handle email launching with multiple fallback approaches
  static Future<Map<String, dynamic>> _handleEmailLaunching(String recipient, String content, String? subject) async {
    final emailSubject = subject ?? 'Message from AI Assistant';
    
    // First try Android email intent if on Android
    if (Platform.isAndroid) {
      try {
        const emailChannel = MethodChannel('com.ahamai.email_intent');
        final result = await emailChannel.invokeMethod('sendEmailWithAttachment', {
          'recipient': recipient,
          'subject': emailSubject,
          'body': content,
        });
        
        if (result['success'] == true) {
          return {
            'success': true,
            'operation': 'send_email',
            'message': 'Email app opened via Android intent',
            'recipient': recipient,
            'method': 'android_intent',
          };
        }
      } catch (e) {
        print('Android email intent failed: $e');
      }
    }
    
    // Try different email URL schemes in order of preference
    final emailUrls = [
      // Standard mailto
      'mailto:$recipient?subject=${Uri.encodeComponent(emailSubject)}&body=${Uri.encodeComponent(content)}',
      // Alternative mailto format
      'mailto:?to=$recipient&subject=${Uri.encodeComponent(emailSubject)}&body=${Uri.encodeComponent(content)}',
      // Simple mailto without parameters (let user fill in)
      'mailto:$recipient',
    ];

    for (int i = 0; i < emailUrls.length; i++) {
      try {
        final uri = Uri.parse(emailUrls[i]);
        final canLaunch = await canLaunchUrl(uri);
        
        if (canLaunch) {
          await launchUrl(uri, mode: LaunchMode.externalApplication);
          return {
            'success': true,
            'operation': 'send_email',
            'message': 'Email app opened successfully',
            'recipient': recipient,
            'method': 'mailto_${i + 1}',
          };
        }
      } catch (e) {
        print('Email attempt ${i + 1} failed: $e');
        continue;
      }
    }

    return {
      'success': false,
      'error': 'Could not open email app. Please check if you have an email app installed (Gmail, Outlook, etc.)',
      'suggestions': [
        'Install Gmail or another email app',
        'Try sharing the file instead',
        'Use WhatsApp or SMS for text messages',
      ],
    };
  }

  /// Generic URL launcher with better error handling
  static Future<Map<String, dynamic>> _launchUrl(String urlString, String appName) async {
    try {
      final uri = Uri.parse(urlString);
      final canLaunch = await canLaunchUrl(uri);
      
      if (canLaunch) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
        return {
          'success': true,
          'message': '$appName opened successfully',
        };
      } else {
        return {
          'success': false,
          'error': 'Cannot open $appName. Make sure you have the app installed.',
        };
      }
    } catch (e) {
      return {
        'success': false,
        'error': 'Failed to open $appName: $e',
      };
    }
  }
  
  /// Get list of available tools
  static Future<List<String>> getAvailableTools() async {
    return [
      'create_file',
      'send_email',
      'send_whatsapp',
      'send_sms',
      'share_file',
    ];
  }
  
  /// Get capabilities of a specific tool
  static Future<Map<String, dynamic>> getToolCapabilities(String toolName) async {
    switch (toolName) {
      case 'create_file':
        return {
          'name': 'File Creation Tool',
          'description': 'Creates files with content in various formats',
          'supported_formats': ['txt', 'html', 'css', 'pdf', 'json', 'xml', 'md'],
          'parameters': ['fileName', 'content', 'fileType', 'metadata'],
        };
      case 'send_email':
        return {
          'name': 'Email Tool',
          'description': 'Opens email app with pre-filled content',
          'parameters': ['recipient', 'subject', 'content'],
        };
      case 'send_whatsapp':
        return {
          'name': 'WhatsApp Tool',
          'description': 'Opens WhatsApp with pre-filled message',
          'parameters': ['recipient', 'content'],
        };
      case 'send_sms':
        return {
          'name': 'SMS Tool',
          'description': 'Opens SMS app with pre-filled message',
          'parameters': ['recipient', 'content'],
        };
      case 'share_file':
        return {
          'name': 'File Sharing Tool',
          'description': 'Shares files via email, WhatsApp, or system share',
          'parameters': ['filePath', 'shareMethod', 'recipient', 'subject', 'message'],
        };
      default:
        return {
          'error': 'Unknown tool: $toolName',
        };
    }
  }
}